### ISSUE TITLE
Ext Auth logs do not show proper version

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#4231]
**Describe the bug**
When following the tutorial for ext auth plugins (https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/plugin_auth/), the functionality works, but the ext auth logs keep showing 'version:undefined'. 

**To Reproduce**
1. Follow the docs outline [here](https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/plugin_auth/)

**Expected behavior**
I would expect the logs to include the proper version of the running build, not undefined.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge > 1.6.4
- Cross repo reference: the real issue is https://github.com/solo-io/ext-auth-service/issues/158.

**Comment by kdorosh** [comment]
fixed on master, backporting to 1.6 @npolshakova

**Comment by sam-heilbron** [comment]
fixed on 1.6 as well

**Comment by sam-heilbron** [comment]
This still appears to be an issue for logs originating from ext-auth. Logs from a 1.7.0-beta10 release:

```
{"level":"info","ts":"2021-02-24T15:04:24.398Z","caller":"runner/xds.go:121","msg":"got 1 new configs","version":"1.7.0-beta10"}
{"level":"info","ts":"2021-02-24T15:04:24.398Z","caller":"runner/xds.go:125","msg":"{\"auth_config_ref_name\":\"gloo-system.oidc-dex\",\"configs\":[{\"AuthConfig\":{\"Oauth2\":{\"OauthType\":{\"OidcAuthorizationCode\":{\"client_id\":\"gloo\",\"issuer_url\":\"http://dex.gloo-system.svc.cluster.local:32000/\",\"app_url\":\"http://subdomain.example.com:8080/\",\"callback_path\":\"/callback\",\"scopes\":[\"email\"],\"session\":{\"cookie_options\":{\"not_secure\":true},\"Session\":null}}}}}}]}","version":"1.7.0-beta10"}
{"level":"info","ts":1614179065.414495,"logger":"ext-auth","msg":"finished unary call with code NotFound","version":"undefined","grpc.start_time":"2021-02-24T15:04:25Z","grpc.request.deadline":"2021-02-24T15:04:30Z","system":"grpc","span.kind":"server","grpc.service":"grpc.health.v1.Health","grpc.method":"Check","error":"rpc error: code = NotFound desc = unknown service","grpc.code":"NotFound","grpc.time_ms":0.07100000232458115}
{"level":"debug","ts":1614179075.1288848,"logger":"ext-auth.ext-auth-service","msg":"Received auth request","version":"undefined","request":{"attributes":{"source":{"address":{"Address":{"SocketAddress":{"address":"127.0.0.1","PortSpecifier":{"PortValue":47210}}}}},"destination":{"address":{"Address":{"SocketAddress":{"address":"127.0.0.1","PortSpecifier":{"PortValue":8080}}}}},"context_extensions":{"config_id":"gloo-system.oidc-dex","source_name":"gloo-system.gateway-proxy-listener-::-8080-gloo-system_petclinic","source_type":"virtual_host"},"request":{"time":1614179075.127614,"http":{"body":"","host":"other.example.com:8080","fragment":"","method":"GET","path":"/","scheme":"","size":0,"query":"","protocol":"HTTP/1.1","id":"17095499443943093420","headers":{"upgrade-insecure-requests":"1",":path":"/",":method":"GET","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","accept-language":"en-US,en;q=0.9","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",":authority":"other.example.com:8080","x-request-id":"adf6ea8f-0808-4d9f-b4eb-68b24c5b5c6c","accept-encoding":"gzip, deflate","x-forwarded-proto":"http","cache-control":"max-age=0"}}}}}}
```

The first 2 log lines originate from gloo and have the version. The next 2 originate from ext-auth and still have version undefined.
