### ISSUE TITLE
glooctl uninstall leaves the crds

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#433]
when we uninstall, we just delete the namespace, we should also delete the CRDs that were registered

**Comment by marcogschmidt** [comment]
Currently we just cascade-delete namespaces, so all non-namespaced resources are ignored by the `uninstall` command. We should clean up all non-namespaced resources (crds, (cluster)roles, (cluster)rolebindings, etc.)

**Comment by rickducott** [comment]
See also #527, uninstall needs to be configurable with the least-regrettable default. 

I'm envisioning something like:

- `glooctl uninstall` deletes any deployments, replicasets, services with gloo label in the `gloo-system` namespace
- `glooctl uninstall -n foo` does the same but for namespace `foo`
- `glooctl uninstall --delete-namespace` removes the namespace (and by extension anything inside the namespace)
- `glooctl uninstall --delete-cluster-resources` removes the gloo crds (and by extension custom gloo objects), CRBs, etc
- `glooctl uninstall --all` deletes everything including namespace, CRDs, CRB, etc. 

I'm not married to any of these specific flag names but think these cover the use cases

**Comment by scranton** [comment]
We should not delete user created artifacts, virtual services and such, without explicit opt in from user, as uninstalling Gloo does not always mean to the user that all their objects will also be deleted. Leaving, by default, user created artifacts like virtual services, means that we can not default to uninstalling CRDs.

For example, its not unusual that a user may uninstall and reinstall a new version of Gloo, and they would expect all of their virtual services and such to remain in place...

We either need to allow users to explicitly opt-in to "we're going to delete everything" AND/OR give big warnings when we're about to delete artifacts Gloo did not create as part of its installation.

**Comment by rickducott** [comment]
I think we're in sync, going to proceed based on the options I articulated above. Please chime in if you'd prefer other option names.

**Comment by rickducott** [comment]
A fix for this was released in 0.12.0, but there was a bug that was fixed in 0.13.0

**Comment by CelsoSantos** [comment]
As of gloo 0.18.4, I after `gloo uninstall` I can still see some CRDs left behind, namely:

```
$ kubectl get crd --all-namespaces

NAME                              CREATED AT
gateways.gateway.solo.io.v2       2019-08-08T09:26:00Z
proxies.gloo.solo.io              2019-08-08T09:26:00Z
settings.gloo.solo.io             2019-08-08T09:26:00Z
upstreamgroups.gloo.solo.io       2019-08-08T09:26:01Z
upstreams.gloo.solo.io            2019-08-08T09:26:00Z
virtualservices.gateway.solo.io   2019-08-08T09:26:00Z
```

**Comment by rickducott** [comment]
@CelsoSantos see the discussion above, use `glooctl uninstall --all` or `glooctl uninstall --delete-crds` to remove the CRDs. We didn't make this the default because it is not desirable in all cases.
